### ISSUE TITLE
Orgdb Package Request

### ISSUE THREAD

**Issue by gvp681** [Yunqing-Yu/tef-abscission-zone#2]
Hello!

I was wondering how to install the following organism package for clusterprofiler in R. I have not been able to locate it on the Bioconductor query page. 

#Install SvOrgDb from local for the 1st run 
install.packages("/Users/yunqingyu/Dropbox/postdoc/data/fonio_tef_ERAC/RNAseq/tef_AZ_202012/clusterProfiler/org.Etef.eg.db",repos = NULL, type="source")

Best,
Kirsten

**Comment by Yunqing-Yu** [comment]
Thanks for the comments. I will send it through email.
